---

name: CI
on: [push]

jobs:

  test:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'
          architecture: 'x64'

      - name: Install dependencies
        run: |
          sudo apt install docker
          python -m pip install --upgrade pip
          pip install ansible==2.10.* ansible-lint==5.0.*
          pip install molecule molecule-docker

      - name: test docker role using Molecule
        run: molecule test
